#define IDR_RIMVS				101
#define IDR_VEHICLEONEVS                        102
#define IDR_VEHICLETWOVS                        103
#define IDR_WORLDPS				104
#define IDR_GLOSSVS				105
#define IDR_GLOSSPS				106
#define IDR_CURVEPS				107
#define IDR_VCSVEHICLEVS                        108
#define IDR_GRADINGPS				109
